db.drones.insertOne()

const Mavic2Enterprise = {
    name: "Mavic 2 Enterprise",
    price: 2499,
    category: "enterprise",
    description: "Designed to empower a new generation of workers, the Mavic 2 Enterprise is the ultimate expression of a tool that delivers beyond expectation to meet current workplace challenges and future demands.",
    icon1: "/images/inspire2icon1.png",
    spec1: "Zoom camera",
    icon2: "/images/inspire2icon2.png",
    spec2: "Dual camera",
    icon3: "/images/inspire2icon3.png",
    spec3: "OcuSync 2.0",
    icon4: "/images/inspire2icon4.png",
    spec4: "Modular Accessories",
    icon5: "/images/inspire2icon5.png",
    spec5: "Password Protection",
    icon6: "/images/inspire2icon6.png",
    spec6: "DJI AirSense",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/enterprise-drones%2Fmavic-2-enterprise-iii.png?alt=media&token=a79bed80-6e0f-46f4-8ac1-7c5a3086207f",
}

const Matrice100 = {
    name: "Matrice 100",
    price: 3599,
    category: "enterprise",
    description: "The DJI Matrice 100 is a fully customizable and programmable flight platform that lets you to turn your ideas and dreams into reality. Equipped with DJI’s easy-to-fly technology and optimized for easy programming through the DJI SDK, the Matrice 100 is ready to carry any sensors, devices that you want to put into the sky.",
    icon1: "/images/zenmusex7icon1.png",
    spec1: "Dual battery support",
    icon2: "/images/zenmusex7icon2.png",
    spec2: "Universal Power and Communication Ports",
    icon3: "/images/zenmusex7icon3.png",
    spec3: "Powerful Propulsion System",
    icon4: "/images/zenmusex7icon4.png",
    spec4: "Flight time: 40 MINS",
    icon5: "/images/zenmusex7icon5.png",
    spec5: "Customizable mounting and balancing",
    icon6: "/images/zenmusex7icon6.png",
    spec6: "Dedicated remote controller",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/enterprise-drones%2Fzenmuse-z30-ii.png?alt=media&token=c66d640c-8e06-4dc7-b570-d090c0397968",
}

const Matrice200 = {
    name: "Matrice 200",
    price: 8199,
    category: "enterprise",
    description: "The ultimate platform for aerial productivity combines a rugged design and simple configurability to work as a solution for a variety of industrial applications.",
    icon1: "/images/zenmusex7icon1.png",
    spec1: "38 Min Max Flight-time",
    icon2: "/images/zenmusex7icon2.png",
    spec2: "Anti-Collision Beacon",
    icon3: "/images/zenmusex7icon3.png",
    spec3: "OcuSync 2.0",
    icon4: "/images/zenmusex7icon4.png",
    spec4: "8 km Transmission Range",
    icon5: "/images/zenmusex7icon5.png",
    spec5: "TimeSync",
    icon6: "/images/zenmusex7icon6.png",
    spec6: "Multiple Payload Configurations",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/enterprise-drones%2Fmatrice-200v2.png?alt=media&token=ab81e126-2156-4b05-a40f-c00dbcd239fa",
}

const Matrice600Pro = {
    name: "Matrice 600 Pro",
    price: 5699,
    category: "enterprise",
    description: "The Matrice 600 Pro (M600 Pro) inherits everything from the M600 with improved flight performance and better loading capacity.",
    icon1: "/images/zenmusex7icon1.png",
    spec1: "A3 Pro Flight Controller",
    icon2: "/images/zenmusex7icon2.png",
    spec2: "Extended Flight Time and Transmission Range",
    icon3: "/images/zenmusex7icon3.png",
    spec3: "Aerial Imaging Solution",
    icon4: "/images/zenmusex7icon4.png",
    spec4: "Professional HD Transmission",
    icon5: "/images/zenmusex7icon5.png",
    spec5: "Complete Integration, Ultra Convenient",
    icon6: "/images/zenmusex7icon6.png",
    spec6: "Charge Six Batteries Simultaneously",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/enterprise-drones%2Fzenmuse-z30-iii.png?alt=media&token=3ddd2e62-0b1d-4893-862f-a4dd622a71c9",
}
