db.drones.insertOne()

const Inspire2 = {
    name: "Inspire 2",
    price: 3399,
    category: "professional",
    description: "Image quality, power and intelligence to meet the needs of professional filmmakers and enterprises around the globe.",
    name: "Inspire 2",
    icon1: "<MdAirplanemodeActive />",
    spec1: "Flight Time: 23-27 MINS",
    icon2: "<FiLoader />",
    spec2: "Control Range: 7 KM",
    icon3: "<MdTimer />",
    spec3: "Speed: 94 KM/H",
    icon4: "<FiVideo />",
    spec4: "Video Resolution: 6K/5.2K",
    icon5: "<FiRadio />",
    spec5: "Sensory Range: 30 M",
    icon6: "<FiYoutube />",
    spec6: "Live View: 1080 P",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/professional-drones%2Finspire-2.png?alt=media&token=89b10030-b6dc-462a-8446-bca2f2562961",
}

const ZenmuseX7 = {
    name: "Zenmuse X7",
    price: 2999,
    category: "professional",
    description: "Fully compatible with the DJI Inspire 2, the Zenmuse X7 is a compact Super 35 camera with an integrated gimbal made for high-end filmmaking.",
    icon1: "<FiCheckSquare />",
    spec1: "Inspire 2 Compatibility",
    icon2: "<FaCloudscale />",
    spec2: "Weight: 449g",
    icon3: "<FiRadio />",
    spec3: "Super 35 Sensor",
    icon4: "<FiCamera />",
    spec4: "14 Stops of Dynamic Range",
    icon5: "<FiVideo />",
    spec5: "6K CinemaDNG",
    icon6: "<FiImage />",
    spec6: "24 MP Stills",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/professional-drones%2Fzenmuse-x7-ii.png?alt=media&token=53d07051-d3d5-40d8-b860-1dcd1c44b3aa",
}

const ZenmuseX4S = {
    name: "Zenmuse X4S",
    price: 999,
    category: "professional",
    description: "The Zenmuse X4S is a powerful camera featuring a 20 megapixel 1-inch sensor and a maximum ISO of 12,800.",
    icon1: "<FiCheckSquare />",
    spec1: "Inspire 2 Compatibility",
    icon2: "<FiRadio />",
    spec2: "1-inch Sensor",
    icon3: "<FiCamera />",
    spec3: "11.6 Stops of Dynamic Range",
    icon4: "<FiImage />",
    spec4: "20 MP Stills",
    icon5: "<FiVideo />",
    spec5: "Video Resolution: 4K 60FPS",
    icon6: "<FiAperture />",
    spec6: "Leaf Shutter",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/professional-drones%2Fzenmuse-x4s-iv.png?alt=media&token=83fcd931-7647-472e-a5c7-f0a54e854e1e",
}

const RoninS = {
    name: "Ronin-S",
    price: 749,
    category: "professional",
    description: "Designed in a single-handed form factor for DSLR and mirrorless cameras, the Ronin-S empowers creators to shoot with the freedom of stabilized shots on the move.",
    icon1: "<FiSliders />",
    spec1: "Superior 3-Axis Stabilization",
    icon2: "<FaCloudscale />",
    spec2: "3.6 kg Tested Payload Capacity",
    icon3: "<FiCamera />",
    spec3: "Camera Control",
    icon4: "<FiCheckSquare />",
    spec4: "Pro Accessory Compatibility",
    icon5: "<FiBatteryCharging />",
    spec5: "Max Battery Life: 12 hrs",
    icon6: "<FiStar />",
    spec6: "Automated Smart Features",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/professional-drones%2Fronin-s.png?alt=media&token=6243cb8b-c301-4c72-ab85-7e23028df556",
}