db.drones.insertOne()

const Mavic2Enterprise = {
    name: "Mavic 2 Enterprise",
    price: 2499,
    category: "enterprise",
    description: "Designed to empower a new generation of workers, the Mavic 2 Enterprise is the ultimate expression of a tool that delivers beyond expectation to meet current workplace challenges and future demands.",
    icon1: "<FiZoomIn />",
    spec1: "Zoom Camera",
    icon2: "<FiCamera />",
    spec2: "Dual Camera",
    icon3: "<FiRadio />",
    spec3: "OcuSync 2.0",
    icon4: "<FiLayers />",
    spec4: "Modular Accessories",
    icon5: "<FiLock />",
    spec5: "Password Protection",
    icon6: "<FiNavigation />",
    spec6: "DJI AirSense",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/enterprise-drones%2Fmavic-2-enterprise-iii.png?alt=media&token=a79bed80-6e0f-46f4-8ac1-7c5a3086207f",
}

const Matrice100 = {
    name: "Matrice 100",
    price: 3599,
    category: "enterprise",
    description: "The DJI Matrice 100 is a fully customizable and programmable flight platform that lets you to turn your ideas and dreams into reality. Equipped with DJI’s easy-to-fly technology and optimized for easy programming through the DJI SDK, the Matrice 100 is ready to carry any sensors, devices that you want to put into the sky.",
    icon1: "<FiBatteryCharging />",
    spec1: "Dual Battery Support",
    icon2: "<FiSettings />",
    spec2: "Universal Power and Communication Ports",
    icon3: "<MdToys />",
    spec3: "Powerful Propulsion System",
    icon4: "<MdAirplanemodeActive />",
    spec4: "Flight Time: 40 MINS",
    icon5: "<FiLayers />",
    spec5: "Expansion Bays",
    icon6: "<MdSettingsRemote />",
    spec6: "Dedicated Remote Controller",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/enterprise-drones%2Fzenmuse-z30-ii.png?alt=media&token=c66d640c-8e06-4dc7-b570-d090c0397968",
}

const Matrice200 = {
    name: "Matrice 200",
    price: 8199,
    category: "enterprise",
    description: "The ultimate platform for aerial productivity combines a rugged design and simple configurability to work as a solution for a variety of industrial applications.",
    icon1: "<MdAirplanemodeActive />",
    spec1: "Flight Time: 38 MINS",
    icon2: "<MdLightbulbOutline />",
    spec2: "Anti-Collision Beacon",
    icon3: "<FiRadio />",
    spec3: "OcuSync 2.0",
    icon4: "<FiNavigation />",
    spec4: "DJI AirSense",
    icon5: "<FiClock />",
    spec5: "TimeSync",
    icon6: "<FiSettings />",
    spec6: "Multiple Payload Configurations",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/enterprise-drones%2Fmatrice-200v2.png?alt=media&token=ab81e126-2156-4b05-a40f-c00dbcd239fa",
}

const Matrice600Pro = {
    name: "Matrice 600 Pro",
    price: 5699,
    category: "enterprise",
    description: "The Matrice 600 Pro (M600 Pro) inherits everything from the M600 with improved flight performance and better loading capacity.",
    icon1: "<MdSettingsRemote />",
    spec1: "A3 Pro Flight Controller",
    icon2: "<MdAirplanemodeActive />",
    spec2: "Extended Flight Time and Transmission Range",
    icon3: "<FiImage />",
    spec3: "Aerial Imaging Solution",
    icon4: "<MdHd />",
    spec4: "Professional HD Transmission",
    icon5: "<FiCheckSquare />",
    spec5: "Complete Integration, Ultra Convenient",
    icon6: "<FiBatteryCharging />",
    spec6: "Charge Six Batteries Simultaneously",
    imageURL: "https://firebasestorage.googleapis.com/v0/b/shoolix.appspot.com/o/enterprise-drones%2Fzenmuse-z30-iii.png?alt=media&token=3ddd2e62-0b1d-4893-862f-a4dd622a71c9",
}
